use org;
select FIRST_NAME AS Worker_name from Worker; 
select upper(FIRST_NAME) from Worker;
select distinct DEPARTMENT from Worker;
select substring(FIRST_NAME,1,3) from Worker;
select INSTR(FIRST_NAME, BINARY'a') from Worker where FIRST_NAME = 'Amitabh';

select rtrim(FIRST_NAME) from Worker;
select ltrim(DEPARTMENT) from Worker;
select distinct length(DEPARTMENT) from Worker;
select replace(FIRST_NAME,'b','B') from Worker;
select concat(FIRST_NAME, ' ', LAST_NAME) as 'COMPLETE_NAME' from Worker;
select * from Worker order by FIRST_NAME asc;
select * from Worker order by FIRST_NAME asc,DEPARTMENT desc;
select * from Worker where FIRST_NAME in ('Vipul','Satish');
select * from Worker where FIRST_NAME not in ('Vipul','Satish');
select * from Worker where DEPARTMENT like 'admin%';
select * from Worker where FIRST_NAME like '%n%';
select * from Worker where FIRST_NAME like '%a';
select * from Worker where FIRST_NAME like '_____a';
select * from Worker where SALARY between 100000 and 500000;
select count(*) from worker WHERE DEPARTMENT = 'Admin';